### PR TITLE
Add README.md to repo

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This PR starts the process of adding a `README.md` file to this repo by extracting the `jostler` section of the Autoloading Design Doc.

Images and links to documents that are not public were removed but they can incrementally be added later.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/jostler/29)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
Since design docs are often updated, would it make sense to just leave the sections that are relevant to this repo (e.g., `jostler `operation, configuration, and operation) in the `README` and add a link to the design doc for further information? 

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/29#-:-NMV6ydCEhx77CIbySP6:b-rrqh1v)* status: 0 of 1 approvals obtained

**Comment by SaiedKazemi** [comment]
Yes, it makes perfect sense and I will do that.  For now, I just wanted to have a `README.md` file in the repo because a few people are interested in learning more about `jostler`.

Thank you for your review.

**Review by cristinaleonr — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/29)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`README.md` line 128 at r2](https://reviewable.io/reviews/m-lab/jostler/29#-NMdh2Rv6d6kaHn-JPDP:-NMdh2Rv6d6kaHn-JPDQ:bslxw7m) ([raw file](https://github.com/m-lab/jostler/blob/ffac6ca5ca2a8934d3e77b73878c96552537a496/README.md#L128)):*
> ```Markdown
> 
> Version 1 of a JSONL bundle will look like the following, pretty printed,
> abbreviated, and showing standard column names in boldface:
> ```

The boldface does not show up here.
___
*[`README.md` line 294 at r2](https://reviewable.io/reviews/m-lab/jostler/29#-NMdh_8K5q2zNGKIJt-9:-NMdh_8K5q2zNGKIJt-A:b8wnida) ([raw file](https://github.com/m-lab/jostler/blob/ffac6ca5ca2a8934d3e77b73878c96552537a496/README.md#L294)):*
> ```Markdown
> `jostler` architecture will consist of two major packages.  One package,
> called `watchdir`, will watch a directory where new format JSON files
> are created.  The other package, called `bundlejson`, will bundle these
> ```

This is called `jsonlbundle`.

**Comment by SaiedKazemi** [comment]
*[`README.md` line 128 at r2](https://reviewable.io/reviews/m-lab/jostler/29#-NMdh2Rv6d6kaHn-JPDP:-NMduBJF0e5eCNebAJM5:bt2vr1b) ([raw file](https://github.com/m-lab/jostler/blob/ffac6ca5ca2a8934d3e77b73878c96552537a496/README.md#L128)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

The boldface does not show up here.
</blockquote></details>

Fixed.

**Comment by SaiedKazemi** [comment]
*[`README.md` line 294 at r2](https://reviewable.io/reviews/m-lab/jostler/29#-NMdh_8K5q2zNGKIJt-9:-NMe2qzu6iA45vn_dnAf:biz8n0i) ([raw file](https://github.com/m-lab/jostler/blob/ffac6ca5ca2a8934d3e77b73878c96552537a496/README.md#L294)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

This is called `jsonlbundle`.
</blockquote></details>

Thanks for noticing this.  I updated the whole paragraph.

**Pull request merged**
