### PR TITLE
Improve test code

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This commit improves test code in cmd/jostler/main_test.go and test/test.sh.  It also improves naming and comments.

There are no major functional changes in this commit.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/jostler/6)

### CODE REVIEW

**Review by robertodauria — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/6#-:-NFTcKA60cjHBfP7945B:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`cmd/jostler/main_test.go` line 23 at r1](https://reviewable.io/reviews/m-lab/jostler/6#-NFTTR3XBF2yvbIXkoPh:-NFTTR3XBF2yvbIXkoPi:blidwaa) ([raw file](https://github.com/m-lab/jostler/blob/c945f7658aea3737354797f09597490756dd2316/cmd/jostler/main_test.go#L23)):*
> ```Go
> 	testExpr       = "jostler"
> 	testDatatype   = "foo1"
> 	testSchemaFile = "foo1::testdata/foo1:-schema.json"
> ```

Is this intentionally `::`?



_Code quote:_
```Go
testSchema
```
___
*[`test/test.sh` line 14 at r1](https://reviewable.io/reviews/m-lab/jostler/6#-NFTcCp8D7qMqxWE5z9y:-NFTcCp8D7qMqxWE5z9z:b-i2sk5b) ([raw file](https://github.com/m-lab/jostler/blob/c945f7658aea3737354797f09597490756dd2316/test/test.sh#L14)):*
> ```Shell
> # they must be manually deleted.
> #
> # Once there is a datatype schema, the script runs `jostler` in the #
> ```

Typo: extra `#`?

**Comment by SaiedKazemi** [comment]
*[`cmd/jostler/main_test.go` line 23 at r1](https://reviewable.io/reviews/m-lab/jostler/6#-NFTTR3XBF2yvbIXkoPh:-NFUEsaxCZLuF8nLGNdV:b6ehty3) ([raw file](https://github.com/m-lab/jostler/blob/c945f7658aea3737354797f09597490756dd2316/cmd/jostler/main_test.go#L23)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Is this intentionally `::`?
</blockquote></details>

No, it's a typo but because the file doesn't exist anyway, the test worked as expected.

I fixed it.

**Comment by SaiedKazemi** [comment]
*[`test/test.sh` line 14 at r1](https://reviewable.io/reviews/m-lab/jostler/6#-NFTcCp8D7qMqxWE5z9y:-NFUFOww3t0-hPvpur10:bss4a2b) ([raw file](https://github.com/m-lab/jostler/blob/c945f7658aea3737354797f09597490756dd2316/test/test.sh#L14)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Typo: extra `#`?
</blockquote></details>

Removed.

**Comment by SaiedKazemi** [comment]
Thank you.

**Pull request merged**
