### PR TITLE
Initial commit of jostler source code

### PR DESCRIPTION
**Pull request by SaiedKazemi**
The watchdir and uploadbundle packages in this initial commit are minimal in order to avoid burdening the code review process with a lot of code.  This commit compiles as is and once it is merged actual code the implement watchdir and uploadbundle will be added in similar steps.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/jostler/1)

### CODE REVIEW

**Review by robertodauria — CHANGES_REQUESTED** [review]
I had a first look at this PR -- please see my comments below.

I guess you also have unit tests for uploadbundle and watchdir but you will commit them later when adding the actual implementations, right?

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/1#-:-NDheyqgEeL-i_ZXlDZh:bsdeb31)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`.golangci.yml` line 8 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhq2CE5ESDTyMvH5mm:-NDhq2CF2t2tunXWtthk:b-d5vql5) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/.golangci.yml#L8)):*
> ```YAML
> linters:
>   enable-all: true
>   disable:
> ```

I did not go through the disabled linters one by one to see what they do specifically, I trust you that these settings make sense :)
___
*[`main.go` line 66 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhSivAEQahxzjrMT3J:-NDhSivAEQahxzjrMT3K:bgtmh6c) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L66)):*
> ```Go
> 
> 	// Parse the host name which should be a string similar to
> 	// mlab4.abc0t.measurement-lab.org into its components.
> ```

Nit: The hostname format should be `$machine-$site.$project.measurement-lab.org` -- e.g. `mlab4-abc0t.mlab-sandbox.measurement-lab.org` 
___
*[`main.go` line 90 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDheCny7hGr-_cP2OVE:-NDheCny7hGr-_cP2OVF:bsbgsoj) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L90)):*
> ```Go
> 	}
> 	// Wait until all goroutines have terminated which, unless there
> 	// is an error, should never happen.
> ```

What happens if a single watcher or bundleUploader goroutine fails? This comment makes me think that on any error all the goroutines would be terminated, is that what actually happens?
___
*[`main.go` line 136 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhWl375eYKsfjhcwBC:-NDhWl375eYKsfjhcwBD:bp9yhvu) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L136)):*
> ```Go
> // via the command line for each datatype.  For example, for
> // datatype foo1, it would be: foo1:</path/to>/<foo1-golden-row.json>.
> func validateGoldenRow(datatype string) (string, error) {
> ```

This func does a bit more than just validating -- it searches for a golden row file for the given datatype, checks that it's formally valid JSON, trims `\n` at the end and returns the file content as a string. Also, the function name implies that the first argument is the golden row (either as a path or as `[]byte`), so I find `datatype` here a bit surprising.

Would you be willing to consider renaming it to something like `goldenRowForDatatype(datatype string) (string, error)` ? It can still return the golden row content as a string, or it could just return the golden row path (to be subsequently read/validated by another func), or it could return the content as a `[]byte` (again, to be validated by another func)
___
*[`main.go` line 145 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhUtbB5A5nrcxuroLJ:-NDhUtbB5A5nrcxuroLK:b-58jc96) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L145)):*
> ```Go
> 	}
> 	if gRowFile == "" {
> 		return "", fmt.Errorf("failed to find golden row for datatype %v", datatype)
> ```

If I saw this error in the logs I would assume the golden row file isn't present on disk, not that its path hasn't been specified at all. Perhaps something like `datatype %v has no corresponding golden row file`?
___
*[`main.go` line 153 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhbOo9D6Uj5U6Q5m6O:-NDhbOo9D6Uj5U6Q5m6P:bj4rhzr) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L153)):*
> ```Go
> 		return "", err
> 	}
> 	if !json.Valid(gRowBytes) {
> ```

Nit: It would help to also know what the unmarshalling error is (especially when testing/writing JSON by hand, knowing that I missed a `,` on line 83 is nice)
___
*[`main.go` line 160 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDheoe16Md1dInH5T-G:-NDheoe16Md1dInH5T-H:bxjf0y0) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L160)):*
> ```Go
> 
> // startWatcher starts a directory watcher goroutine that watches the
> // specified directory and notfies its client of new (and potentially
> ```

Typo: "notifies"
___
*[`main.go` line 161 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhei1d8cvUa6noS7wa:-NDhei1e1zEQSKr7XUCd:bakeg0u) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L161)):*
> ```Go
> // startWatcher starts a directory watcher goroutine that watches the
> // specified directory and notfies its client of new (and potentially
> // missed)files.
> ```

Typo: blank space after `)`
___
*[`main.go` line 166 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhff6E9MByy6FNImWo:-NDhff6E9MByy6FNImWp:bvikm9c) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L166)):*
> ```Go
> 	wdClient, err := watchdir.New(watchDir, extensions, watchEvents, *missedAgeMin, *missedInterval)
> 	if err != nil {
> 		return nil, fmt.Errorf("failed to instantiate watcher: %w", err)
> ```

Nit: This will output `failed to start directory watcher: failed to instantiate watcher: <actual error>` -- what would you think of just returning `nil, err` here so the error message is only added once? The same reasoning applies to `failed to instantiate uploader` in `startBundleUploader`.
___
*[`main.go` line 180 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhgUue32xCSSoipIrt:-NDhgUue32xCSSoipIru:b-uusdxa) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L180)):*
> ```Go
> }
> 
> // startBundleUploader start a bundle uploader goroutine that bundles
> ```

Typo: "starts" 
___
*[`main.go` line 181 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhgbth0WhLpbdVrsVB:-NDhgbth0WhLpbdVrsVC:b-lxirpc) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L181)):*
> ```Go
> 
> // startBundleUploader start a bundle uploader goroutine that bundles
> // individual JSON files into JSONL bundle and uploads it to GCS.
> ```

Typo: Not sure if "into a (single) JSONL bundle"  or "into JSONL bundles" is what you meant here.
___
*[`main.go` line 215 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhi6SeBkidOjpsSlcJ:-NDhi6Sf4x0-G5d-4cDB:b-rmeog) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L215)):*
> ```Go
> // "filename:line-number function()" printed in green and the message
> // printed in blue for easier visual inspection.
> func vLogf(format string, args ...interface{}) {
> ```

This is cool! :)
___
*[`uploadbundle/uploadbundle.go` line 3 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhkXgP9RHQrF72aKCq:-NDhkXgP9RHQrF72aKCr:bbnpehy) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/uploadbundle/uploadbundle.go#L3)):*
> ```Go
> // Package uploadbundle bundles multiple JSON files on the local
> // filesystem into a single JSON Lines (JSONL) file and uploads the bundle
> // to Google Could Storage (GCS).
> ```

Typo: Cloud
___
*[`uploadbundle/uploadbundle.go` line 9 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhlHaVBrBFaWNCDBpQ:-NDhlHaVBrBFaWNCDBpR:b-sph2n9) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/uploadbundle/uploadbundle.go#L9)):*
> ```Go
> //  1. Be in date subdirectories (<yyyy>/<mm>/<dd>) of a data directory
> //     configured via BundleConfig.DataDir.
> //  2. Have pathnames that conform to regexp `[^a-zA-Z0-9/:._-]` and
> ```

Nit: I think you meant `[a-zA-Z0-9\/:._-]+`? (without the `^` or it would only match whitespace characters or similar)
___
*[`uploadbundle/uploadbundle.go` line 61 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDho0Ma37SUQ4kiXsK6:-NDho0Ma37SUQ4kiXsK7:bq6x9en) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/uploadbundle/uploadbundle.go#L61)):*
> ```Go
> 
> // Verbose provides a convenient way for the caller to enable verbose
> // printing and control its format (mostfly for debugging).
> ```

Typo: mostly
___
*[`watchdir/watchdir.go` line 93 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhonst0T22mS_4Qlbn:-NDhonsu-I-x84JkX_uI:b-tpy46k) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/watchdir/watchdir.go#L93)):*
> ```Go
> }
> 
> // WatchAndNotify watches a directory (and possiblty all its subdirectories)
> ```

Typo: possibly

**Comment by SaiedKazemi** [comment]
Yes, the unit tests for packages will be added along with the full implementation of the packages.

I almost always include a test for the main package too and will do that after this PR is merged.

**Comment by SaiedKazemi** [comment]
*[`.golangci.yml` line 8 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhq2CE5ESDTyMvH5mm:-NDtl38Q74gjAZpXOKR7:biotu45) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/.golangci.yml#L8)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I did not go through the disabled linters one by one to see what they do specifically, I trust you that these settings make sense :)
</blockquote></details>

This file isn't really needed but I added it to the repo to make it convenient for collaborators to run `golangci-lint run ./...` to lint their changes.

Please note that some of the linters aren't really useful and force their author's style preference.  I've updated the file so it's more clear now what some linters are disabled.

**Comment by SaiedKazemi** [comment]
*[`main.go` line 66 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhSivAEQahxzjrMT3J:-NDtoqxw8HIi-KPoUnrC:bsj646i) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L66)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: The hostname format should be `$machine-$site.$project.measurement-lab.org` -- e.g. `mlab4-abc0t.mlab-sandbox.measurement-lab.org` 
</blockquote></details>

Corrected.

**Comment by SaiedKazemi** [comment]
*[`main.go` line 90 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDheCny7hGr-_cP2OVE:-NDtq8jwE-s3nfVikc85:b-bu4qy9) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L90)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

What happens if a single watcher or bundleUploader goroutine fails? This comment makes me think that on any error all the goroutines would be terminated, is that what actually happens?
</blockquote></details>

I updated the comment to be more clear.  I also successfully tested the case where multiple goroutines were running but had to terminate due to context cancelation.

**Comment by SaiedKazemi** [comment]
*[`main.go` line 136 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhWl375eYKsfjhcwBC:-NDtrXmn4ZJPmg_lDWi9:bhoijoh) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L136)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

This func does a bit more than just validating -- it searches for a golden row file for the given datatype, checks that it's formally valid JSON, trims `\n` at the end and returns the file content as a string. Also, the function name implies that the first argument is the golden row (either as a path or as `[]byte`), so I find `datatype` here a bit surprising.

Would you be willing to consider renaming it to something like `goldenRowForDatatype(datatype string) (string, error)` ? It can still return the golden row content as a string, or it could just return the golden row path (to be subsequently read/validated by another func), or it could return the content as a `[]byte` (again, to be validated by another func)
</blockquote></details>

You are right and `goldenRowForDatatype` is a much better name.

The motivation for returning `string` was that the golden row could be easily added to each bundle without requiring further validation, conversion, etc.  However, per my last meeting with Stephen and Cristina, handling golden row will be different so this function will change in a future PR.

**Comment by SaiedKazemi** [comment]
*[`main.go` line 145 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhUtbB5A5nrcxuroLJ:-NDttDRlDXS4QN0EnowK:b-m9bl6z) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L145)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

If I saw this error in the logs I would assume the golden row file isn't present on disk, not that its path hasn't been specified at all. Perhaps something like `datatype %v has no corresponding golden row file`?
</blockquote></details>

The `--golden-row` flag is now optional and its default value is `/var/spool/<experiment>/<datatype>/golden-row.json` so the function and this error message are little different now.

**Comment by SaiedKazemi** [comment]
*[`main.go` line 153 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhbOo9D6Uj5U6Q5m6O:-NDtu9f24uZINGWKURpl:bo98eww) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L153)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: It would help to also know what the unmarshalling error is (especially when testing/writing JSON by hand, knowing that I missed a `,` on line 83 is nice)
</blockquote></details>

Unfortunately, `json.Valid()` does not return an error so I changed it to `json.Unmarshal()`.  However, while the error says what went wrong, it does not include a line number.

**Comment by SaiedKazemi** [comment]
*[`main.go` line 160 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDheoe16Md1dInH5T-G:-NDtynfhAvpSP-SPtp1H:b-o374ab) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L160)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Typo: "notifies"
</blockquote></details>

Thanks for catching this.  I wonder why `codespell` caught other typos but not this one!

**Comment by SaiedKazemi** [comment]
*[`main.go` line 161 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhei1d8cvUa6noS7wa:-NDtzTKO4Kdrz8Jlr0JO:b-896fix) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L161)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Typo: blank space after `)`
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
*[`main.go` line 166 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhff6E9MByy6FNImWo:-NDtzzh81SX1fYwTo9tc:baaau14) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L166)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: This will output `failed to start directory watcher: failed to instantiate watcher: <actual error>` -- what would you think of just returning `nil, err` here so the error message is only added once? The same reasoning applies to `failed to instantiate uploader` in `startBundleUploader`.
</blockquote></details>

The intention of wrapping the error is to provide more context for what failed.  In this particular case, there is only one error (`failed to instantiate watcher`) so perhaps wrapping the error from the `watchdir` package does not add more useful information.  But if this function is extended in the future and can have multiple conditions that return error, it is recommended that errors be wrapped to provide more context.

If you are not strongly opposed to it, I suggest we leave it as is.

**Comment by SaiedKazemi** [comment]
*[`main.go` line 180 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhgUue32xCSSoipIrt:-NDu0P2Q5rGAUEK7aKb5:b-896fix) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L180)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Typo: "starts" 
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
*[`main.go` line 181 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhgbth0WhLpbdVrsVB:-NDu0ieMAp-ofsjGqvfI:by960dk) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/main.go#L181)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Typo: Not sure if "into a (single) JSONL bundle"  or "into JSONL bundles" is what you meant here.
</blockquote></details>

Updated the comment.

**Comment by SaiedKazemi** [comment]
*[`uploadbundle/uploadbundle.go` line 3 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhkXgP9RHQrF72aKCq:-NDu11Xe0KtmJHVaFKuR:b-896fix) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/uploadbundle/uploadbundle.go#L3)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Typo: Cloud
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
*[`uploadbundle/uploadbundle.go` line 9 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhlHaVBrBFaWNCDBpQ:-NDu3OkT58qgwnB-_fJ3:b-lxr022) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/uploadbundle/uploadbundle.go#L9)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: I think you meant `[a-zA-Z0-9\/:._-]+`? (without the `^` or it would only match whitespace characters or similar)
</blockquote></details>

I updated the comment to specifically mention the basename with this format: `^[a-zA-Z0-9][a-zA-Z0-9:._-]*.json`

**Comment by SaiedKazemi** [comment]
*[`uploadbundle/uploadbundle.go` line 61 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDho0Ma37SUQ4kiXsK6:-NDu41h85MmOwBM3HozM:bzhcfvl) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/uploadbundle/uploadbundle.go#L61)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Typo: mostly
</blockquote></details>

Thanks for catching all these typos.  I am puzzled why the spell checker tools catch some typos and miss others!!

**Comment by SaiedKazemi** [comment]
*[`watchdir/watchdir.go` line 93 at r1](https://reviewable.io/reviews/m-lab/jostler/1#-NDhonst0T22mS_4Qlbn:-NDu4QBqBAZVznLLk6t4:b-896fix) ([raw file](https://github.com/m-lab/jostler/blob/d5b1bcacdd9843cb5df4c75f981b741925d3776b/watchdir/watchdir.go#L93)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Typo: possibly
</blockquote></details>

Done.

**Review by SaiedKazemi — COMMENTED** [review]
@robertodauria thank you so much for your detailed code review and excellent feedback.  PTAL.

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/1#-:-NDu6-W52zYf90-fOWv1:b-u74ko6)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)

**Review by robertodauria — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/1#-:-NE0zjiH6pWjSpMJOw-9:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
