### PR TITLE
Improve code organization and add test for package main

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This commit moves all command line processing from main.go to cli.go
and adds main_test.go and associated test files.  Test coverage is currently
at 87.4%.

There are no significant changes to the application logic.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/jostler/4)

### CODE REVIEW

**Review by robertodauria — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/4)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`cmd/jostler/cli.go` line 89 at r2](https://reviewable.io/reviews/m-lab/jostler/4#-NEpj6qX1z0aOiASXrtE:-NEpj6qX1z0aOiASXrtF:b-8yd7s5) ([raw file](https://github.com/m-lab/jostler/blob/4408445a5d7c9dae8d7afa8b5733cab38357cd47/cmd/jostler/cli.go#L89)):*
> ```Go
> 	// flagx.StringArray always appends to the array and there is no
> 	// way to remove an element from it.
> 	extensions = nil
> ```

Thanks for explaining :)
___
*[`cmd/jostler/cli.go` line 117 at r2](https://reviewable.io/reviews/m-lab/jostler/4#-NEpjSTk7t0sXjDD_YQO:-NEpjSTk7t0sXjDD_YQP:b-k8dg1f) ([raw file](https://github.com/m-lab/jostler/blob/4408445a5d7c9dae8d7afa8b5733cab38357cd47/cmd/jostler/cli.go#L117)):*
> ```Go
> 		// Parse the M-Lab hostname (which should be in one of the
> 		// following formats) into its constituent parts.
> 		// v1: <machine>.<site>.measuremen-lab.org
> ```

Typo: measurement
___
*[`cmd/jostler/cli.go` line 118 at r2](https://reviewable.io/reviews/m-lab/jostler/4#-NEpjUuT3ePG5Sa3fqDI:-NEpjUuT3ePG5Sa3fqDJ:b-11xw13) ([raw file](https://github.com/m-lab/jostler/blob/4408445a5d7c9dae8d7afa8b5733cab38357cd47/cmd/jostler/cli.go#L118)):*
> ```Go
> 		// following formats) into its constituent parts.
> 		// v1: <machine>.<site>.measuremen-lab.org
> 		// v2: <machine>.<site>.<project>.measurement-lab.org
> ```

`<machine>-<site>.<project>.measurement-lab.org`
___
*[`cmd/jostler/cli.go` line 135 at r2](https://reviewable.io/reviews/m-lab/jostler/4#-NEpjopL8IYSxkA6B3aB:-NEpjopL8IYSxkA6B3aC:b-6xlsii) ([raw file](https://github.com/m-lab/jostler/blob/4408445a5d7c9dae8d7afa8b5733cab38357cd47/cmd/jostler/cli.go#L135)):*
> ```Go
> // datatype has been specified.
> func validateSchemaFlags() error {
> 	if len(schemaFiles) > len(datatypes) {
> ```

Nit: Did you mean `!=` here? The returned error says "unequal schemas and datatype". I see the point of not returning here `if len(schemaFiles) < len(datatypes)` to check precisely which datatype does not have an associated schema, though. Perhaps the error could be more specific?

**Comment by SaiedKazemi** [comment]
*[`cmd/jostler/cli.go` line 117 at r2](https://reviewable.io/reviews/m-lab/jostler/4#-NEpjSTk7t0sXjDD_YQO:-NEpqBYsBYcu2tMEifA-:b-vj63a3) ([raw file](https://github.com/m-lab/jostler/blob/4408445a5d7c9dae8d7afa8b5733cab38357cd47/cmd/jostler/cli.go#L117)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Typo: measurement
</blockquote></details>

Thank you for noticing this.  I need to find out why the spell-checker doesn't catch these typos.

**Comment by SaiedKazemi** [comment]
*[`cmd/jostler/cli.go` line 135 at r2](https://reviewable.io/reviews/m-lab/jostler/4#-NEpjopL8IYSxkA6B3aB:-NEprSDPEUxM7Ka0EFm6:biyd3h5) ([raw file](https://github.com/m-lab/jostler/blob/4408445a5d7c9dae8d7afa8b5733cab38357cd47/cmd/jostler/cli.go#L135)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: Did you mean `!=` here? The returned error says "unequal schemas and datatype". I see the point of not returning here `if len(schemaFiles) < len(datatypes)` to check precisely which datatype does not have an associated schema, though. Perhaps the error could be more specific?
</blockquote></details>

Because `-schema-file` is optional, `!=` won't work and will generate false positives.  I changed the error message to: `more schema files than datatypes` so it's more clear.

**Comment by SaiedKazemi** [comment]
*[`cmd/jostler/cli.go` line 118 at r2](https://reviewable.io/reviews/m-lab/jostler/4#-NEpjUuT3ePG5Sa3fqDI:-NEpsecP0xWDLFbHRDea:b-896fix) ([raw file](https://github.com/m-lab/jostler/blob/4408445a5d7c9dae8d7afa8b5733cab38357cd47/cmd/jostler/cli.go#L118)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

`<machine>-<site>.<project>.measurement-lab.org`
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
Thank you Roberto.  PTAL.

**Comment by SaiedKazemi** [comment]
*[`cmd/jostler/cli.go` line 118 at r2](https://reviewable.io/reviews/m-lab/jostler/4#-NEpjUuT3ePG5Sa3fqDI:-NEptI2s9CJywsLxvKRl:b-896fix) ([raw file](https://github.com/m-lab/jostler/blob/4408445a5d7c9dae8d7afa8b5733cab38357cd47/cmd/jostler/cli.go#L118)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by robertodauria — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/4#-:-NEpuyfA0LQ6QlRt6aBR:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by SaiedKazemi** [comment]
@robertodauria thank you for your review.

**Pull request merged**
