### PR TITLE
Update standard columns to use civil.Date

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change updates the StandardColumnV0 wrapping structure's `date` column from a `string` type to a `civil.Date` type so that `bigquery.InferSchema` correctly identifies this as a `DATE` column type.

Since the format of the string and `civil.Date`, previously recorded data should still be compatible with the new schema. However, before any data can be autoloaded, the new schema will need to be deployed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/jostler/46)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
This will require more care.

**Comment by stephen-soltesz** [comment]
@cristinaleonr - I think this is ready now.

**Review by cristinaleonr — APPROVED** [review]
I am amazed at the number of changes required. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/46#-:-NS7YVpL7ovWz136jBG9:b4i0cvw)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by cristinaleonr — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/46#-:-NS7YtdKCOOMJbDiNb7g:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
Thank you.

**Pull request merged**
