### PR TITLE
Add unit tests for package gcs

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This commit adds unit tests for package gcs.  As part of this addition, a few other files needed minor edits (e.g., for name changes).  Packge gcs gets 100% coverage.

The changes pass golangci-lint, go test -race ./..., and e2e tests as described in test/README.txt.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/jostler/16)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/16)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`internal/gcs/gcs.go` line 20 at r1](https://reviewable.io/reviews/m-lab/jostler/16#-NHQ_CSkBrol7XJb4nfh:-NHQ_CSkBrol7XJb4nfi:bijqm4d) ([raw file](https://github.com/m-lab/jostler/blob/d3a13b9a02e75efa68c80a18ef4d0f7a9cac10d8/internal/gcs/gcs.go#L20)):*
> ```Go
> 
> type StorageClient struct {
> 	Download     func(context.Context, string) ([]byte, error)
> ```

An interface that two concrete types implement, I can understand. I don't understand why we need function pointers here instead of two concrete types that implement the same interface.

If the StorageClient is meant to be generic and support two types of backends (GCS, or local disk) then I would expect the constructor of this type to accept an "uploader/downloader" interface with two implementations, or similar, right?

What am I missing?
___
*[`internal/testhelper/testhelper.go` line 67 at r1](https://reviewable.io/reviews/m-lab/jostler/16#-NHQZJxaCF9nuQ12qzKB:-NHQZJxaCF9nuQ12qzKC:b-qoqlm6) ([raw file](https://github.com/m-lab/jostler/blob/d3a13b9a02e75efa68c80a18ef4d0f7a9cac10d8/internal/testhelper/testhelper.go#L67)):*
> ```Go
> }
> 
> func DiskNewClient(ctx context.Context, bucket string) (*gcs.StorageClient, error) {
> ```

I see this is an internal package, but the function is still public for the package. Did you intend to remove the docstring?

**Comment by SaiedKazemi** [comment]
*[`internal/gcs/gcs.go` line 20 at r1](https://reviewable.io/reviews/m-lab/jostler/16#-NHQ_CSkBrol7XJb4nfh:-NHQo7QCBFrDsj4PtCHH:bv0iokx) ([raw file](https://github.com/m-lab/jostler/blob/d3a13b9a02e75efa68c80a18ef4d0f7a9cac10d8/internal/gcs/gcs.go#L20)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

An interface that two concrete types implement, I can understand. I don't understand why we need function pointers here instead of two concrete types that implement the same interface.

If the StorageClient is meant to be generic and support two types of backends (GCS, or local disk) then I would expect the constructor of this type to accept an "uploader/downloader" interface with two implementations, or similar, right?

What am I missing?
</blockquote></details>

The motivations for changing from an interface to a concrete type were conformance with Go style guidelines:

  1. Accept interfaces, return concrete types
  2. Interfaces belong in the package that consumes values of the interface.

Regarding 2, this is easily done when there is one consumer but here we have more than one (uploadbundle.go and testhelper.go), so either the same interface has to be defined in each consumer (creating undesirable duplicity) or defined in the producer package (violating the guideline).

I hope it's clear.  I am open and in fact welcome other implement ideas but I think it will be a lot easier and faster to discuss interactively if possible.

**Comment by SaiedKazemi** [comment]
*[`internal/testhelper/testhelper.go` line 67 at r1](https://reviewable.io/reviews/m-lab/jostler/16#-NHQZJxaCF9nuQ12qzKB:-NHQtwA39V58LgoWO5j3:b-ys3u3a) ([raw file](https://github.com/m-lab/jostler/blob/d3a13b9a02e75efa68c80a18ef4d0f7a9cac10d8/internal/testhelper/testhelper.go#L67)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I see this is an internal package, but the function is still public for the package. Did you intend to remove the docstring?
</blockquote></details>

I added its docstring and also changed Download() and Upload() because they don't have to be exported.

**Review by SaiedKazemi — COMMENTED** [review]
Thank you for your review @stephen-soltesz . PTAL.

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/16#-:-NHQuSrjEQ9hYEkIDEJN:bu1e1x7)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — APPROVED** [review]
This need not be blocking, but I really don't think this is a pattern we want to repeat.

:lgtm:

> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/16#-:-NHR1rrO9jYnRULV39hb:b-gqb2j8)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`internal/gcs/gcs.go` line 20 at r1](https://reviewable.io/reviews/m-lab/jostler/16#-NHQ_CSkBrol7XJb4nfh:-NHQx3s9-jTtGk67L-BV:bcp35ab) ([raw file](https://github.com/m-lab/jostler/blob/d3a13b9a02e75efa68c80a18ef4d0f7a9cac10d8/internal/gcs/gcs.go#L20)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

The motivations for changing from an interface to a concrete type were conformance with Go style guidelines:

  1. Accept interfaces, return concrete types
  2. Interfaces belong in the package that consumes values of the interface.

Regarding 2, this is easily done when there is one consumer but here we have more than one (uploadbundle.go and testhelper.go), so either the same interface has to be defined in each consumer (creating undesirable duplicity) or defined in the producer package (violating the guideline).

I hope it's clear.  I am open and in fact welcome other implement ideas but I think it will be a lot easier and faster to discuss interactively if possible.
</blockquote></details>

Well these are guidelines, not rules. So, it's okay to be flexible in our judgement in order to find the right balance between the spirit and the consequence. It's difficult for me to accept that function pointers are preferable here. When you take a step back, is your sense that this is the right starting point for new object definitions in the future? That we landed here suggests to me that we took a wrong turn along the way of trade offs.

Given the trade offs you've described, for example, I would probably treat separate packages as separate and maybe have two tiny interface definitions to prevent needing function pointers in this struct. Or, if that was more offensive to us, then a single interface definition that other packages reference. Or a third package just to define that interface. Maybe this is taste. But, I would not recommend using function pointers in this way in the future. Another way is to solicit feedback from go readability reviewers.

**Comment by SaiedKazemi** [comment]
*[`internal/gcs/gcs.go` line 20 at r1](https://reviewable.io/reviews/m-lab/jostler/16#-NHQ_CSkBrol7XJb4nfh:-NHR3Uh22jlS_AeUYY5S:bcs882t) ([raw file](https://github.com/m-lab/jostler/blob/d3a13b9a02e75efa68c80a18ef4d0f7a9cac10d8/internal/gcs/gcs.go#L20)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Well these are guidelines, not rules. So, it's okay to be flexible in our judgement in order to find the right balance between the spirit and the consequence. It's difficult for me to accept that function pointers are preferable here. When you take a step back, is your sense that this is the right starting point for new object definitions in the future? That we landed here suggests to me that we took a wrong turn along the way of trade offs.

Given the trade offs you've described, for example, I would probably treat separate packages as separate and maybe have two tiny interface definitions to prevent needing function pointers in this struct. Or, if that was more offensive to us, then a single interface definition that other packages reference. Or a third package just to define that interface. Maybe this is taste. But, I would not recommend using function pointers in this way in the future. Another way is to solicit feedback from go readability reviewers.
</blockquote></details>

I totally agree with you and will revisit when I have a block of time.  I'd also like to use this an opportunity to interactively discuss with you (and other interested team members) the pros and cons of the different approaches I tried.

**Comment by SaiedKazemi** [comment]
Thank you for your review.

**Pull request merged**
