### PR TITLE
Add full implementation of watchdir package

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This commit adds full implementation of the watchdir package along with its unit test.

The unit test coverage is currently 85% but will be improved in a future commit.

The new code passes golangci-lint and go test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/jostler/8)

### CODE REVIEW

**Review by robertodauria — CHANGES_REQUESTED** [review]
Tests are failing for me:
```
=== RUN   TestWatchAndNotify
    watchdir_test.go:183: >>> test 00 no file creation
2022/11/02 13:11:33 watchdir.go:136: watchdir.(*WatchDir).WatchAndNotify(): watching directory /home/roberto/git/jostler/internal/watchdir/testdata and notifying
2022/11/02 13:11:33 watchdir.go:195: watchdir.(*WatchDir).findMissedAndNotify(): scanning /home/roberto/git/jostler/internal/watchdir/testdata every 1s to find missed files
2022/11/02 13:11:33 lstat /home/roberto/git/jostler/internal/watchdir/testdata: no such file or directory
panic: lstat /home/roberto/git/jostler/internal/watchdir/testdata: no such file or directory

goroutine 11 [running]:
log.Panic({0xc000057f28?, 0xc00001e240?, 0xc00005c7c0?})
	/usr/lib/go-1.18/src/log/log.go:385 +0x65
github.com/m-lab/jostler/internal/watchdir.(*WatchDir).WatchAndNotify(0xc0000266c0, {0x56ef00?, 0xc00007e800})
	/home/roberto/git/jostler/internal/watchdir/watchdir.go:139 +0x20b
created by github.com/m-lab/jostler/internal/watchdir.TestWatchAndNotify
	/home/roberto/git/jostler/internal/watchdir/watchdir_test.go:197 +0x7ea
FAIL	github.com/m-lab/jostler/internal/watchdir	0.005s
FAIL
```

Perhaps you have an additional `testdata` folder that hasn't been committed?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/8#-:-NFsFGbq83FrlTFjJ6YW:b-8o5qcr)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`internal/watchdir/watchdir.go` line 72 at r1](https://reviewable.io/reviews/m-lab/jostler/8#-NFsSFRG9EGRZAFNeNev:-NFsSFRG9EGRZAFNeNew:b-8r0grq) ([raw file](https://github.com/m-lab/jostler/blob/ddf4d3091437ec5452b9f0dc7e7b7bbbda3506aa/internal/watchdir/watchdir.go#L72)):*
> ```Go
> 	errUnrecognizedEvent = errors.New("unrecognized event")
> 
> 	watchChanSize     = 10000
> ```

Is this value arbitrary? In any case, a named constant here might be clearer and simplify future changes.

**Review by robertodauria — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/8#-:-NFtDJh_0ZfpRocoT1Ai:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`internal/watchdir/watchdir.go` line 130 at r1](https://reviewable.io/reviews/m-lab/jostler/8#-NFt7gkqD-IJ2c0LEK9w:-NFt7gkqD-IJ2c0LEK9x:b-tpy46k) ([raw file](https://github.com/m-lab/jostler/blob/ddf4d3091437ec5452b9f0dc7e7b7bbbda3506aa/internal/watchdir/watchdir.go#L130)):*
> ```Go
> }
> 
> // WatchAndNotify watches a directory (and possiblty all its subdirectories)
> ```

Typo: possibly

**Review by robertodauria — COMMENTED** [review]
Please consider adding continuous integration to this repository (automated testing and code coverage reports on commit) as part of the next PR or in a small dedicated one. :slightly_smiling_face: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/8#-:-NFtDUavCwgVJqGeEz4C:b4mz9iu)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

**Review by robertodauria — CHANGES_REQUESTED** [review]
I just realized there's another test failure (one more reason to automate running tests in a "clean" environment):
```
panic: lstat /var/spool/jostler: no such file or directory

goroutine 39 [running]:
log.Panic({0xc000077ef8?, 0xc00060aae0?, 0xc000385e20?})
	/usr/lib/go-1.18/src/log/log.go:385 +0x65
github.com/m-lab/jostler/internal/watchdir.(*WatchDir).WatchAndNotify(0xc000572ae0, {0xd47fb0?, 0xc0001fce80})
	/home/roberto/git/jostler/internal/watchdir/watchdir.go:139 +0x20b
github.com/m-lab/jostler/cmd/jostler.startWatcher.func1(0x0?)
	/home/roberto/git/jostler/cmd/jostler/main.go:158 +0x49
created by github.com/m-lab/jostler/cmd/jostler.startWatcher
	/home/roberto/git/jostler/cmd/jostler/main.go:156 +0x272
FAIL	github.com/m-lab/jostler/cmd/jostler	0.637s
?   	github.com/m-lab/jostler/internal/gcs	[no test files]
```

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/8#-:-NFtEUdKCQg82t-lriaO:bq2g42c)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

**Comment by SaiedKazemi** [comment]
Thank you @robertodauria for your review.

Since I wanted to get this PR to you by the start of your day, there wasn't enough time to do exhaustive unit and integration testing.  Now that the code is reviewed, I will do exhaustive testing before merging the PR.

**Comment by SaiedKazemi** [comment]
*[`internal/watchdir/watchdir.go` line 72 at r1](https://reviewable.io/reviews/m-lab/jostler/8#-NFsSFRG9EGRZAFNeNev:-NFyglJ3DAhV2rLZuBFK:b-4h62d7) ([raw file](https://github.com/m-lab/jostler/blob/ddf4d3091437ec5452b9f0dc7e7b7bbbda3506aa/internal/watchdir/watchdir.go#L72)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Is this value arbitrary? In any case, a named constant here might be clearer and simplify future changes.
</blockquote></details>

These values are inspired by `pusher` and somewhat arbitrary.  I made them named constants.

**Comment by SaiedKazemi** [comment]
*[`internal/watchdir/watchdir.go` line 130 at r1](https://reviewable.io/reviews/m-lab/jostler/8#-NFt7gkqD-IJ2c0LEK9w:-NFyh7_Z2PCVjyojdqPy:b-896fiz) ([raw file](https://github.com/m-lab/jostler/blob/ddf4d3091437ec5452b9f0dc7e7b7bbbda3506aa/internal/watchdir/watchdir.go#L130)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Typo: possibly
</blockquote></details>

Done,

**Review by SaiedKazemi — COMMENTED** [review]
PTAL

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/8#-:-NFytbZq56RpyF-Pyx0H:bb71pro)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)

**Review by stephen-soltesz — APPROVED** [review]
At @saiedkazemi 's request the last set of changes lgtm. I defer to @robertodauria for all earlier changes or the coherence of the whole change.

> Reviewed 3 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/8#-:-NFyvyA89SK_JUHrgRMX:bgnyix6)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @robertodauria and @SaiedKazemi)

___
*[`internal/uploadbundle/uploadbundle.go` line 46 at r4](https://reviewable.io/reviews/m-lab/jostler/8#-NFyve653LO7lOcIOd1L:-NFyve653LO7lOcIOd1M:b-t92k95) ([raw file](https://github.com/m-lab/jostler/blob/18f481961ed0cb728924623a5bc5160b1ed25e1c/internal/uploadbundle/uploadbundle.go#L46)):*
> ```Go
> type GCSConfig struct {
> 	Bucket  string // GCS bucket name
> 	DataDir string // "path" to datatype subdirectory in GCS (e.g., /autoload/v0/tables/<experiment>/<datatype>.table.json)
> ```

Note: unlike unix filesystems, GCS objects should not be prefixed with '/' this causes unexpected errors between systems.

**Comment by SaiedKazemi** [comment]
*[`internal/uploadbundle/uploadbundle.go` line 46 at r4](https://reviewable.io/reviews/m-lab/jostler/8#-NFyve653LO7lOcIOd1L:-NFyxiQp6Zp48WsE1pf4:bp7ep7i) ([raw file](https://github.com/m-lab/jostler/blob/18f481961ed0cb728924623a5bc5160b1ed25e1c/internal/uploadbundle/uploadbundle.go#L46)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Note: unlike unix filesystems, GCS objects should not be prefixed with '/' this causes unexpected errors between systems.
</blockquote></details>

The leading slash in the object name was meant to serve as the separator from the bucket name, not part of the object name (gsutil ls gs://bucket/object).  But I will remove it to avoid confusion.

**Comment by SaiedKazemi** [comment]
Thank you for your review.

**Comment by stephen-soltesz** [comment]
@robertodauria if there were any changes remaining in your review, please add them still so they can be addressed in future PRs.

**Comment by robertodauria** [comment]
No further changes remaining, this LGTM. Thanks.

**Pull request merged**
