### PR TITLE
Split uploadbundle into two packages

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This commit splits the uploadbundle package into two packages: uploadbundle and jsonlbundle.

To perform unit, integration, and e2e testing, this commit also includes changes to the testhelper package (as its name suggests, the testhelper package is solely for testing purposes and its code is not compiled into the build).
    
All changes successfully pass golangci-lint and go test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/jostler/13)

### CODE REVIEW

**Review by robertodauria — CHANGES_REQUESTED** [review]
Thanks! I'm halfway through the review, will post an update in a bit. Meanwhile, I added some comments for `jsonlbundle`.

> Reviewed 8 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/13#-:-NGviB4NDQNr9O5gPqJI:byxolzj)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`internal/jsonlbundle/jsonlbundle.go` line 53 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvNZa95Z24EWvt4IJm:-NGvNZa95Z24EWvt4IJn:b-g5gqrz) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L53)):*
> ```Go
> 	return &JSONLBundle{
> 		Lines:      []string{},
> 		Timestamp:  time.Now().UTC().Format("2006/01/02T150405.000000Z"),
> ```

Nit: `nowUTC.Format(...)`?
___
*[`internal/jsonlbundle/jsonlbundle.go` line 92 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvPow2CvflVBqfdSwM:-NGvPow2CvflVBqfdSwN:b-qyds6h) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L92)):*
> ```Go
> 		Date: jb.DateSubdir,
> 		Archiver: api.ArchiverV0{
> 			Version:    "jostler@0.1.7",
> ```

Please make the version (0.1.7) a variable. We can then use a flag to `go build` to inject the version in the build script and make it part of the CI (tagged release `v0.1.7` -> build `v0.1.7`).

The same applies to `GitCommit` below -- both should start empty or with some placeholder value (`<untagged>`?) so it's immediate to distinguish data produced by development builds vs actual releases.

I'm using the `vX.Y.Z` format (with the `v`) in the examples above as that's how we usually tag releases.
___
*[`internal/jsonlbundle/jsonlbundle.go` line 92 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvQi4tAqWtN3OeojLM:-NGvQi4tAqWtN3OeojLN:btelpsb) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L92)):*
> ```Go
> 		Date: jb.DateSubdir,
> 		Archiver: api.ArchiverV0{
> 			Version:    "jostler@0.1.7",
> ```

Thinking out loud... what if `Version` is just the version number? i.e. "v0.1.7" instead of "jostler@0.1.7"? It's true that we might have a different archiver name in the future, but maybe that deserves its own `Name` field rather than conflating name+version in `Version`? 
___
*[`internal/jsonlbundle/jsonlbundle.go` line 103 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvSsv8AvBcjpn7uju7:-NGvSsv8AvBcjpn7uju8:b-8yzrxn) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L103)):*
> ```Go
> 		log.Panicf("failed to marshal standard columns: %v", err)
> 	}
> 	line := fmt.Sprintf("%s,\"raw\":%s}", strings.TrimSuffix(string(stdColsBytes), "}"), contents)
> ```

Doesn't this add two `raw` fields to the JSON, since `stdCols` already has one?

Could the `StandardColumnsV0.Raw` field be of type `interface{}` (or `any` since we're using Go 1.18+) so you don't need to do string manipulation with a JSON here? It also seems a more natural fit than a string since it will be either a map or a slice (`{}`/`[]` are both valid top-level elements in a JSON-text).
___
*[`internal/jsonlbundle/jsonlbundle.go` line 106 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvcM0J2OIypAxEZKxp:-NGvcM0J2OIypAxEZKxq:bksbdrr) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L106)):*
> ```Go
> 	jb.Lines = append(jb.Lines, line)
> 	jb.FullPaths = append(jb.FullPaths, fullPath)
> 	jb.Size += uint(len(contents))
> ```

`Size` does not include the standard columns bytes. Is this intentional? The description for this field is "size of this bundle" so I would assume it's akin to the file size (or "object size", in GCS-speak) and include the standard column wrapper size, too.
___
*[`internal/jsonlbundle/jsonlbundle.go` line 116 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvdB095s55cfLWZrRr:-NGvdB095s55cfLWZrRs:bi2x01z) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L116)):*
> ```Go
> 	for _, fullPath := range append(jb.FullPaths, jb.BadFiles...) {
> 		verbose("removing %v", fullPath)
> 		if err := os.Remove(fullPath); err != nil {
> ```

Nit: Please add to the docstring that this function will not do anything on failures. In the future this might be a good Prometheus metric to monitor.
___
*[`internal/jsonlbundle/jsonlbundle.go` line 124 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvever1lE3en3oylxf:-NGveves62jeL_lCuepQ:bn62rwp) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L124)):*
> ```Go
> // readJSONFile reads the specified file and returns its contents if it
> // is valid JSON.
> func readJSONFile(fullPath string) (string, error) {
> ```

Same reasoning as above: this can return either a `map[string]interface{}` (if the top-level element is`{}`) or a `[]interface{}` (if it's `[]`) -- perhaps making it return `(any, error)` would make things easier?

**Comment by SaiedKazemi** [comment]
*[`internal/jsonlbundle/jsonlbundle.go` line 53 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvNZa95Z24EWvt4IJm:-NGxNmiG3RvbqsUkiu5w:b-896fix) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L53)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: `nowUTC.Format(...)`?
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
*[`internal/jsonlbundle/jsonlbundle.go` line 92 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvPow2CvflVBqfdSwM:-NGxNr9k8F_cUWlywWIF:b-896fix) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L92)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Please make the version (0.1.7) a variable. We can then use a flag to `go build` to inject the version in the build script and make it part of the CI (tagged release `v0.1.7` -> build `v0.1.7`).

The same applies to `GitCommit` below -- both should start empty or with some placeholder value (`<untagged>`?) so it's immediate to distinguish data produced by development builds vs actual releases.

I'm using the `vX.Y.Z` format (with the `v`) in the examples above as that's how we usually tag releases.
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
*[`internal/jsonlbundle/jsonlbundle.go` line 92 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvQi4tAqWtN3OeojLM:-NGxNvn9-180DX936wq_:bfojhs1) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L92)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Thinking out loud... what if `Version` is just the version number? i.e. "v0.1.7" instead of "jostler@0.1.7"? It's true that we might have a different archiver name in the future, but maybe that deserves its own `Name` field rather than conflating name+version in `Version`? 
</blockquote></details>

Sure, as long as there is no ambiguity in which tool generated the archive,`vX.Y.Z` is fine.

**Comment by SaiedKazemi** [comment]
*[`internal/jsonlbundle/jsonlbundle.go` line 103 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvSsv8AvBcjpn7uju7:-NGxOVUb6ElT7SRRApSB:bld8xyq) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L103)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Doesn't this add two `raw` fields to the JSON, since `stdCols` already has one?

Could the `StandardColumnsV0.Raw` field be of type `interface{}` (or `any` since we're using Go 1.18+) so you don't need to do string manipulation with a JSON here? It also seems a more natural fit than a string since it will be either a map or a slice (`{}`/`[]` are both valid top-level elements in a JSON-text).
</blockquote></details>

I've corrected it and verified via e2e testing that the result looks good.  For example:
`{
  "Date": "2022/11/15",
  "Archiver": {
    ...
  },
  "Raw": {
    "UUID": "1234",
    "ToolVersion": "0.1.2",
    "Result": 100
  }
}`

**Comment by SaiedKazemi** [comment]
*[`internal/jsonlbundle/jsonlbundle.go` line 106 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvcM0J2OIypAxEZKxp:-NGxP7Fl9xE21VGJstlO:b-896fix) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L106)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

`Size` does not include the standard columns bytes. Is this intentional? The description for this field is "size of this bundle" so I would assume it's akin to the file size (or "object size", in GCS-speak) and include the standard column wrapper size, too.
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
*[`internal/jsonlbundle/jsonlbundle.go` line 116 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvdB095s55cfLWZrRr:-NGxPAgEC-RLiL4KelPO:b-896fix) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L116)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: Please add to the docstring that this function will not do anything on failures. In the future this might be a good Prometheus metric to monitor.
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
*[`internal/jsonlbundle/jsonlbundle.go` line 124 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvever1lE3en3oylxf:-NGxPEalCiSYsmMkS748:b-rruqz5) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L124)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Same reasoning as above: this can return either a `map[string]interface{}` (if the top-level element is`{}`) or a `[]interface{}` (if it's `[]`) -- perhaps making it return `(any, error)` would make things easier?
</blockquote></details>

I think returning the contents of a file as `string` is clearer than `map[string]interface{}` or `[]interface{}` especially when there is no need to process the contents (i.e., no need to index the map).  The latter form, returning `[]interface{}` or `any` is actually discouraged because Go style guidelines recommend accepting interface values but returning concrete values.

**Comment by SaiedKazemi** [comment]
*[`internal/jsonlbundle/jsonlbundle.go` line 103 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvSsv8AvBcjpn7uju7:-NGxQQZ6EQLKWrXv6xyH:b-pdwaj5) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L103)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

I've corrected it and verified via e2e testing that the result looks good.  For example:
`{
  "Date": "2022/11/15",
  "Archiver": {
    ...
  },
  "Raw": {
    "UUID": "1234",
    "ToolVersion": "0.1.2",
    "Result": 100
  }
}`
</blockquote></details>

Regarding using `interface{}` or `any`, I had actually initially done it that way but BigQuery does not support it:

```
$ cat main.go
package main

import (
	"log"
	"cloud.google.com/go/bigquery"
)

type Foo struct {
	Date string
	Raw  any
}

func main() {
	if _, err := bigquery.InferSchema(Foo{}); err != nil {
		log.Fatal(err)
	}
}
$ go run main.go 
2022/11/15 14:35:34 bigquery: field "Raw": type interface {} is not supported
exit status 1
$ 
```

**Comment by SaiedKazemi** [comment]
@robertodauria Thank you very much for your review and comments.  PTAL.

When you hav a few minutes for an interactive conversation, I'd like to discuss a couple of things that can further improve code quality and readability and hear your thoughts.

**Review by robertodauria — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/13)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`cmd/jostler/cli.go` line 78 at r2](https://reviewable.io/reviews/m-lab/jostler/13#-NH-5ww3AWXAPz4oQDpw:-NH-5ww3AWXAPz4oQDpx:b1acgw1) ([raw file](https://github.com/m-lab/jostler/blob/8b7887fde1438803240dac554e4d141bfdfbab19/cmd/jostler/cli.go#L78)):*
> ```Go
> 
> 	// Flags related to program's execution.
> 	flag.StringVar(&version, "versiondir", "", "version of this program, usually its release tag (e.g., v0.1.7)")
> ```

I don't think this should be a flag (there's no reason for a user to ever specify it, the version is a property of the build, not determined at runtime -- same for the git commit). It's enough that it is a global variable of the package, so it can be changed [in the build script (see the ndt-server example)](https://github.com/m-lab/ndt-server/blob/main/build.sh#L15)
___
*[`internal/jsonlbundle/jsonlbundle.go` line 103 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvSsv8AvBcjpn7uju7:-NH-8jN94AefB9vDniOO:b-9pvywb) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L103)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Regarding using `interface{}` or `any`, I had actually initially done it that way but BigQuery does not support it:

```
$ cat main.go
package main

import (
	"log"
	"cloud.google.com/go/bigquery"
)

type Foo struct {
	Date string
	Raw  any
}

func main() {
	if _, err := bigquery.InferSchema(Foo{}); err != nil {
		log.Fatal(err)
	}
}
$ go run main.go 
2022/11/15 14:35:34 bigquery: field "Raw": type interface {} is not supported
exit status 1
$ 
```
</blockquote></details>

I think I see the problem. :confused: 

If this struct is ever going to be used to read/write rows directly from BigQuery, then I guess it would not work anyway since `Raw` is declared as a `string` in `StandardColumnsV0` but ends up being an embedded STRUCT in BQ. I believe this string manipulation that marshals a string containing JSON-text (the input file, `contents`) as a JSON object changes the resulting datatype to an incompatible one, but please let me know if I'm missing something here and it's in fact possible to read a STRUCT back into `string` from BigQuery.

There also does not seem to be a corresponding Go type for "JSON object" (even if there is a JSON datatype in BQ) according to [InferSchema's documentation](https://pkg.go.dev/cloud.google.com/go/bigquery?utm_source=godoc#InferSchema).

I agree it's a good idea to discuss this on a VC.
___
*[`internal/jsonlbundle/jsonlbundle.go` line 124 at r1](https://reviewable.io/reviews/m-lab/jostler/13#-NGvever1lE3en3oylxf:-NH-DakF8KjBHd8R6GUz:b18bcps) ([raw file](https://github.com/m-lab/jostler/blob/2abe77f9160b26c8d5195dd17f173a048fef1b53/internal/jsonlbundle/jsonlbundle.go#L124)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

I think returning the contents of a file as `string` is clearer than `map[string]interface{}` or `[]interface{}` especially when there is no need to process the contents (i.e., no need to index the map).  The latter form, returning `[]interface{}` or `any` is actually discouraged because Go style guidelines recommend accepting interface values but returning concrete values.
</blockquote></details>

I agree :slightly_smiling_face: I think the problem I was trying to solve with `interface{}` lies elsewhere (see the other comment about typing).

**Review by robertodauria — APPROVED** [review]
We discussed the remaining changes on a VC. :lgtm: after removing the command-line flags for gitCommit and version. Thanks!

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/13#-:-NH0SVzGBo6YXsgTsGqU:b-fpc4sp)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

**Comment by SaiedKazemi** [comment]
*[`cmd/jostler/cli.go` line 78 at r2](https://reviewable.io/reviews/m-lab/jostler/13#-NH-5ww3AWXAPz4oQDpw:-NH0eFF34jSFcAOF7uL2:b-gfnmrg) ([raw file](https://github.com/m-lab/jostler/blob/8b7887fde1438803240dac554e4d141bfdfbab19/cmd/jostler/cli.go#L78)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I don't think this should be a flag (there's no reason for a user to ever specify it, the version is a property of the build, not determined at runtime -- same for the git commit). It's enough that it is a global variable of the package, so it can be changed [in the build script (see the ndt-server example)](https://github.com/m-lab/ndt-server/blob/main/build.sh#L15)
</blockquote></details>

Made them `version` and `gitCommit` as global variables of package `main`.

**Comment by SaiedKazemi** [comment]
Thank you again for your time and valuable discussions.

**Pull request merged**
