### PR TITLE
Enable Travis CI builds

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This commit adds a .travis.yml file to the repo to enable Travis CI builds.  The modifications to watchdir_test.go remove changes to verbosity and watch event names because they are global and can cause a false race condition.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/jostler/12)

### CODE REVIEW

**Review by robertodauria — APPROVED** [review]
:lgtm: - Thank you! I've also enabled coveralls for this repository (https://coveralls.io/github/m-lab/jostler).

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/12#-:-NGahv1xBF6HyRsyYWD5:b-svizuk)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by robertodauria — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/12)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`.travis.yml` line 6 at r1](https://reviewable.io/reviews/m-lab/jostler/12#-NGb72w3196mqzn4lFQG:-NGb72w3196mqzn4lFQH:bqq4vu6) ([raw file](https://github.com/m-lab/jostler/blob/f8d8389fea7efd0575b7895f7778392d6c887250/.travis.yml#L6)):*
> ```YAML
> 
> before_install:
> - go get github.com/mattn/goveralls
> ```

This should be `go install github.com/mattn/goveralls@latest`. The `after_success` step is currently failing due to the `goveralls` executable not being there, but since it's `after_success` it did not count as a build failure (this is intentional -- goveralls might fail sometimes and we don't want to fail builds just because of that).

Sorry I missed this earlier.

**Comment by SaiedKazemi** [comment]
Great!  Thanks a lot Roberto.

**Comment by SaiedKazemi** [comment]
*[`.travis.yml` line 6 at r1](https://reviewable.io/reviews/m-lab/jostler/12#-NGb72w3196mqzn4lFQG:-NGrMst25nNJ3UYD2Z0R:bhajwqk) ([raw file](https://github.com/m-lab/jostler/blob/f8d8389fea7efd0575b7895f7778392d6c887250/.travis.yml#L6)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

This should be `go install github.com/mattn/goveralls@latest`. The `after_success` step is currently failing due to the `goveralls` executable not being there, but since it's part of the `after_success` step it did not count as a build failure (this is intentional -- goveralls might fail sometimes and we don't want to fail builds just because of that).

Sorry I missed this earlier.
</blockquote></details>

Thank you for noticing this as I also missed it.

**Review by SaiedKazemi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/12#-:-NGrPSns6C36pOX0nT4H:bnfp4nl)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)

**Pull request merged**
