### PR TITLE
Change schema handling code

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This commit changes how table schemas are generated and compared for backward compatibility.

The schema logic is currently still in the main package but will move to its own package in a future PR.

The changes in this PR were tested in the following two ways:
  1. Via cmd/jostler/main_test.go with close to 90% coverage.
  2. Via test/test.sh script, making sure that jostler creates table schema files with standard columns that the bq command tool can use to create a table.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/jostler/5)

### CODE REVIEW

**Review by robertodauria — CHANGES_REQUESTED** [review]
A few general comments:

- This PR is quite big -- it looks OK but fewer LOC would be easier to review and I could probably be more helpful :slightly_smiling_face: 
- I've noticed just now that the Go version is 1.20, which is yet unreleased (and quite far from release, judging by the github [milestone](https://github.com/golang/go/milestone/250)) -- was this intentional? I see that you used `.Abs()` on a `time.Duration` which is a go1.19 feature
- One of the tests is failing:
```
    main_test.go:161: main() = incompatible schema:  1 field(s) only in old schema, wanted ""
FAIL
```

I've just run `go1.19 test ./...`, should I do anything different?

> Reviewed 15 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/5#-:-NFOmTLT0n8XIbidQTnn:b-mqdniq)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`cmd/jostler/cli.go` line 103 at r1](https://reviewable.io/reviews/m-lab/jostler/5#-NFOVy9Y18HV1EU7EUBa:-NFOVy9Y18HV1EU7EUBb:bo8vx2r) ([raw file](https://github.com/m-lab/jostler/blob/815d3e37df549c4059d4fdf6d3217adfcec78ac5/cmd/jostler/cli.go#L103)):*
> ```Go
> 		extensions = []string{".json"}
> 	}
> 	if !*local {
> ```

Nit: Purely for readability, would you consider making `local` and other boolean flags `bool` instead of `*bool`?
___
*[`cmd/jostler/schema.go` line 45 at r1](https://reviewable.io/reviews/m-lab/jostler/5#-NFOqR0a41M23BW6RpJo:-NFOqR0a41M23BW6RpJp:b5asjh8) ([raw file](https://github.com/m-lab/jostler/blob/815d3e37df549c4059d4fdf6d3217adfcec78ac5/cmd/jostler/schema.go#L45)):*
> ```Go
> )
> 
> // createNewTableSchemas creates new table schemas for all datatypes
> ```

Typo: `createNewTableSchemaJSON`
___
*[`test/test.sh` line 6 at r1](https://reviewable.io/reviews/m-lab/jostler/5#-NFOkRlM14BQLvgLxNuv:-NFOkRlM14BQLvgLxNuw:b76pw9j) ([raw file](https://github.com/m-lab/jostler/blob/815d3e37df549c4059d4fdf6d3217adfcec78ac5/test/test.sh#L6)):*
> ```Shell
> 
> readonly TABLES=(
> 	mlab-sandbox:saied.hello1
> ```

Could we use generic names like `jostler-test.hello1` and `jostler-test.foo1` here?
___
*[`test/test.sh` line 9 at r1](https://reviewable.io/reviews/m-lab/jostler/5#-NFOllNPAELYw9gSgdt-:-NFOllNPAELYw9gSgdt0:b-33hyo5) ([raw file](https://github.com/m-lab/jostler/blob/815d3e37df549c4059d4fdf6d3217adfcec78ac5/test/test.sh#L9)):*
> ```Shell
> 	mlab-sandbox:saied.foo1
> 	mlab-sandbox:ndt.scamper1
> 	mlab-cloudflare:speedtest.speed2
> ```

Is `mlab-cloudflare` currently considered "sandbox" or "production"? If the latter, I would be against using it in these tests by default.
___
*[`test/test.sh` line 26 at r1](https://reviewable.io/reviews/m-lab/jostler/5#-NFOlIRk-J1lEApNObCq:-NFOlIRk-J1lEApNObCr:b-5o5jdo) ([raw file](https://github.com/m-lab/jostler/blob/815d3e37df549c4059d4fdf6d3217adfcec78ac5/test/test.sh#L26)):*
> ```Shell
> build() {
> 	#shellcheck disable=SC2046
> 	execute go build -race -o jostler $(find ../cmd/jostler -name '*.go' | grep -v '_test\.go')
> ```

What is the advantage of this vs just `execute go build -race -o jostler ./cmd/jostler`? Could you please add a comment explaining why it's done this way?

**Comment by SaiedKazemi** [comment]
*[`cmd/jostler/cli.go` line 103 at r1](https://reviewable.io/reviews/m-lab/jostler/5#-NFOVy9Y18HV1EU7EUBa:-NFPC45V3fPphXpHvB-W:b-yantuq) ([raw file](https://github.com/m-lab/jostler/blob/815d3e37df549c4059d4fdf6d3217adfcec78ac5/cmd/jostler/cli.go#L103)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: Purely for readability, would you consider making `local` and other boolean flags `bool` instead of `*bool`?
</blockquote></details>

These were pointers because of `flag.Bool()` (and other `flag.Xxx()`) implicit declarations.  But now that we have explicit declarations, it makes sense to use `flag.XxxVar()` to get rid of pointer indirections.

Done.

**Comment by SaiedKazemi** [comment]
*[`cmd/jostler/schema.go` line 45 at r1](https://reviewable.io/reviews/m-lab/jostler/5#-NFOqR0a41M23BW6RpJo:-NFPGUZjAxRSzfAaXZN7:b-ep776c) ([raw file](https://github.com/m-lab/jostler/blob/815d3e37df549c4059d4fdf6d3217adfcec78ac5/cmd/jostler/schema.go#L45)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Typo: `createNewTableSchemaJSON`
</blockquote></details>

Thanks for catching this.

Done.

**Comment by SaiedKazemi** [comment]
*[`test/test.sh` line 6 at r1](https://reviewable.io/reviews/m-lab/jostler/5#-NFOkRlM14BQLvgLxNuv:-NFPH-nCCXxY1BOcid5-:b-iwgsnc) ([raw file](https://github.com/m-lab/jostler/blob/815d3e37df549c4059d4fdf6d3217adfcec78ac5/test/test.sh#L6)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Could we use generic names like `jostler-test.hello1` and `jostler-test.foo1` here?
</blockquote></details>

These are dataset names and should be `${USER}` to work for everyone without stepping on each other.

Done.

**Comment by SaiedKazemi** [comment]
*[`test/test.sh` line 9 at r1](https://reviewable.io/reviews/m-lab/jostler/5#-NFOllNPAELYw9gSgdt-:-NFPJ2Rp4Ks0ObTlVdEE:b-595r1v) ([raw file](https://github.com/m-lab/jostler/blob/815d3e37df549c4059d4fdf6d3217adfcec78ac5/test/test.sh#L9)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Is `mlab-cloudflare` currently considered "sandbox" or "production"? If the latter, I would be against using it in these tests by default.
</blockquote></details>

The schema of `mlab-cloudflare:speedtest.speed2` is only read by `test.sh` and is not created/removed/modified in any way.  Using the schema of `speed2` datatype, `test.sh` creates a table with `standard columns` in `mlab-sandbox:${USER}` dataset.

I think you should be able to see `mlab-sandbox.saied.speed2` table via the following link:https://pantheon.corp.google.com/bigquery?project=mlab-sandbox&supportedpurview=project&d=base_tables&ws=!1m5!1m4!4m3!1smlab-sandbox!2ssaied!3sspeed2

**Comment by SaiedKazemi** [comment]
*[`test/test.sh` line 26 at r1](https://reviewable.io/reviews/m-lab/jostler/5#-NFOlIRk-J1lEApNObCq:-NFPKabQAY-L9RgKsrKX:b-f0piop) ([raw file](https://github.com/m-lab/jostler/blob/815d3e37df549c4059d4fdf6d3217adfcec78ac5/test/test.sh#L26)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

What is the advantage of this vs just `execute go build -race -o jostler ./cmd/jostler`? Could you please add a comment explaining why it's done this way?
</blockquote></details>

During debugging and experimentation, I was creating and/or renaming different files in `../cmd/jostler` and wanted to visually see them but there's no need to see individual filenames anymore, so I changed the line to `execute go build -race -o jostler ../cmd/jostler` as you suggested.

Done.

**Comment by SaiedKazemi** [comment]
Thanks a lot for your review and sorry again about the size of this PR.

Re go1.20, it was set implicitly by the Go runtime environment on my gLinux workstation.  I will change it to go1.18 to match the same version we're using for other M-Lab repos and will send a separate PR for go1.18.

**Comment by SaiedKazemi** [comment]
I looked into the cause of `go test` failure and realized that the failure actually works as expected :) because I had uploaded a schema with an additional field to `pusher-mlab-sandbox:autoload/v0/datatypes/ndt/foo1-schema.json` when I was doing manual testing and forgot to revert my change.

I will add initialization checks to avoid false positives like this when testing.  Thanks for noticing it!

**Review by robertodauria — COMMENTED** [review]
> Reviewed 2 of 19 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/5)* status: 1 change requests, 0 of 1 approvals obtained

**Review by robertodauria — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/5#-:-NFPie1198udNDzSCi9z:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
@SaiedKazemi please add CI to this repo to run unit tests automatically on pushes and PRs.

**Comment by SaiedKazemi** [comment]
@stephen-soltesz yes, of course, it's on my to do list.

**Pull request merged**
