### PR TITLE
Add tools and instructions for e2e testing

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/jostler/15)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
Thanks for this. It will be very useful for testing purposes.

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/15#-:-NH6TojsCOKPg21SQwbc:b-vx1s1l)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`test/schema.sh` line 34 at r2](https://reviewable.io/reviews/m-lab/jostler/15#-NH6Tuu730t_PFde_pyl:-NH6Tuu730t_PFde_pym:b-rp4x63) ([raw file](https://github.com/m-lab/jostler/blob/b45f388307dcb992d636785eec2a52a9ccf36518/test/schema.sh#L34)):*
> ```Shell
> 
> readonly BQ_TABLES=(
> 	#"${PROJECT_ID}:${USER}.hello1"
> ```

Do you need this commented out code?
___
*[`test/schema.sh` line 102 at r2](https://reviewable.io/reviews/m-lab/jostler/15#-NH6UFBw7FsuQ8CXwpg-:-NH6UFBw7FsuQ8CXwpg0:b-h61gll) ([raw file](https://github.com/m-lab/jostler/blob/b45f388307dcb992d636785eec2a52a9ccf36518/test/schema.sh#L102)):*
> ```Shell
> 
> # Prompt the user to verify the datatype schema file does not have
> # standard columns.  If it does, they should be manually deleted.
> ```

What happens if the schema has standard columns and the user does not manually delete them?

**Comment by SaiedKazemi** [comment]
*[`test/schema.sh` line 34 at r2](https://reviewable.io/reviews/m-lab/jostler/15#-NH6Tuu730t_PFde_pyl:-NH6Vy5uAwY3PtHxmX8A:b32gpv7) ([raw file](https://github.com/m-lab/jostler/blob/b45f388307dcb992d636785eec2a52a9ccf36518/test/schema.sh#L34)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Do you need this commented out code?
</blockquote></details>

I commented them out because `hello1` and `foo1` were trivial tables that I used for testing but I wanted to show the user that they can create their own simple tables.  If it's confusing, I can delete them from the script.

**Comment by SaiedKazemi** [comment]
*[`test/schema.sh` line 102 at r2](https://reviewable.io/reviews/m-lab/jostler/15#-NH6UFBw7FsuQ8CXwpg-:-NH6WKaqDS871h-4H6Dc:b8na8we) ([raw file](https://github.com/m-lab/jostler/blob/b45f388307dcb992d636785eec2a52a9ccf36518/test/schema.sh#L102)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

What happens if the schema has standard columns and the user does not manually delete them?
</blockquote></details>

The `raw` will include the standard columns.  For example, for `scamper1` the new table will look like the following:
```
data
archiver
raw
    id
    parser
    date
    raw
```

**Comment by SaiedKazemi** [comment]
I'd appreciate any suggestions you may have to further improve this.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/15#-:-NH6bPo30qjb0Z6x1Akn:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`test/schema.sh` line 34 at r2](https://reviewable.io/reviews/m-lab/jostler/15#-NH6Tuu730t_PFde_pyl:-NH6aPT0CW44cejZ3929:bjuhckm) ([raw file](https://github.com/m-lab/jostler/blob/b45f388307dcb992d636785eec2a52a9ccf36518/test/schema.sh#L34)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

I commented them out because `hello1` and `foo1` were trivial tables that I used for testing but I wanted to show the user that they can create their own simple tables.  If it's confusing, I can delete them from the script.
</blockquote></details>

Ah okay, it was not obvious to me why they were there. It might be helpful to have a comment explaining that.
___
*[`test/schema.sh` line 102 at r2](https://reviewable.io/reviews/m-lab/jostler/15#-NH6UFBw7FsuQ8CXwpg-:-NH6agLQ8julepdw215e:b-t6o8ii) ([raw file](https://github.com/m-lab/jostler/blob/b45f388307dcb992d636785eec2a52a9ccf36518/test/schema.sh#L102)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

The `raw` will include the standard columns.  For example, for `scamper1` the new table will look like the following:
data
archiver
raw
    id
    parser
    date
    raw
</blockquote></details>

I see. I suppose that is okay since the creation of the table is more so a sanity check.

Out of curiosity, what about the schema file created? Would that have all the fields listed above or just the fields in the original table?

**Comment by SaiedKazemi** [comment]
*[`test/schema.sh` line 34 at r2](https://reviewable.io/reviews/m-lab/jostler/15#-NH6Tuu730t_PFde_pyl:-NH6da19DfHCpfEWhM5N:bwc75ma) ([raw file](https://github.com/m-lab/jostler/blob/b45f388307dcb992d636785eec2a52a9ccf36518/test/schema.sh#L34)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Ah okay, it was not obvious to me why they were there. It might be helpful to have a comment explaining that.
</blockquote></details>

Sure, I will add a comment before merging.

**Comment by SaiedKazemi** [comment]
*[`test/schema.sh` line 102 at r2](https://reviewable.io/reviews/m-lab/jostler/15#-NH6UFBw7FsuQ8CXwpg-:-NH6deZ31s0qQa3mgHib:bpaktie) ([raw file](https://github.com/m-lab/jostler/blob/b45f388307dcb992d636785eec2a52a9ccf36518/test/schema.sh#L102)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I see. I suppose that is okay since the creation of the table is more so a sanity check.

Out of curiosity, what about the schema file created? Would that have all the fields listed above or just the fields in the original table?
</blockquote></details>

The table schema file will all the fields: the standard columns that `jostler` uses to wrap the `raw` data, and the `raw` data in its entirety which includes the original standard columns.

As you said, this is only for test purposes to make sure `jostler` creates valid table schema files as actual table creation is outside its scope.

**Comment by SaiedKazemi** [comment]
Thank you for your review.

**Pull request merged**
