### PR TITLE
Revert "Remove Date from M-Lab's standard columns (#25)"

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This reverts commit 9f23fc29d094069cc26fd235c6d6f09df84b4f73.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/jostler/30)

### CODE REVIEW

**Comment by SaiedKazemi** [comment]
@stephen-soltesz @cristinaleonr Per our offline conversation, I have reverted the commit that removed `Date` from standard columns.  Tested the change locally and verified `Date` is in the standard columns:

```
{
  "Date": "2023/01/26",
  "Archiver": {
    "Version": "",
    "GitCommit": "",
    "ArchiveURL": "gs://newclient,download,upload/e2e/gcs/autoload/v1/experiment/datatype1/date=2023-01-26/20230126T140740.065182Z-datatype1-mlab1-lga01-experiment-data.jsonl",
    "Filename": "/usr/local/google/home/saied/work/jostler.github/e2e/local/var/spool/experiment/datatype1/2023/01/26/T140740.064428Z.json"
  },
  "Raw": {
    "UUID": "1234",
    "ToolVersion": "0.1.2",
    "Result": 100
  }
}
```

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/30)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`internal/jsonlbundle/jsonlbundle.go` line 111 at r1](https://reviewable.io/reviews/m-lab/jostler/30#-NMing5cA8RfgJSAaXnC:-NMing5cA8RfgJSAaXnD:b-urtyuq) ([raw file](https://github.com/m-lab/jostler/blob/7060f19caa9232815a80c7dad6d1028923be5c7e/internal/jsonlbundle/jsonlbundle.go#L111)):*
> ```Go
> 	}
> 	stdCols := api.StandardColumnsV0{
> 		Date: jb.DateSubdir,
> ```

IIRC, we identified documentation that required this field to use the YYYY-MM-DD format. Can you confirm? This is present in the comment above, but not in the example output on this PR description.

**Comment by SaiedKazemi** [comment]
*[`internal/jsonlbundle/jsonlbundle.go` line 111 at r1](https://reviewable.io/reviews/m-lab/jostler/30#-NMing5cA8RfgJSAaXnC:-NMisuo95FCd7YmiGYub:b6zrrk4) ([raw file](https://github.com/m-lab/jostler/blob/7060f19caa9232815a80c7dad6d1028923be5c7e/internal/jsonlbundle/jsonlbundle.go#L111)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

IIRC, we identified documentation that required this field to use the YYYY-MM-DD format. Can you confirm? This is present in the comment above, but not in the example output on this PR description.
</blockquote></details>

Good catch!

**Comment by SaiedKazemi** [comment]
The format of `Date` changed to `yyyy-mm-dd` as shown in the following example:

```
jq . e2e/gcs/autoload/v1/experiment/datatype1/date\=2023-01-26/20230126T162857.157071Z-datatype1-mlab1-lga01-experiment-data.jsonl
{
  "Date": "2023-01-26",
  "Archiver": {
    "Version": "",
    "GitCommit": "",
    "ArchiveURL": "gs://newclient,download,upload/e2e/gcs/autoload/v1/experiment/datatype1/date=2023-01-26/20230126T162857.157071Z-datatype1-mlab1-lga01-experiment-data.jsonl",
    "Filename": "/usr/local/google/home/saied/work/jostler.revert/e2e/local/var/spool/experiment/datatype1/2023/01/26/T162857.156239Z.json"
  },
  "Raw": {
    "UUID": "1234",
    "ToolVersion": "0.1.2",
    "Result": 100
  }
}
...
```

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/30#-:-NMjEPGN1PLV4Hj5NuHj:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
