### PR TITLE
Add uploadbundle package

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This commit adds the uploadbundle package to jostler.  Package unit tests for uploadbundle are not in this commit but a new tool (data.go) is added to the test directory for more exhaustive integration testing as described in test/README.txt.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/jostler/11)

### CODE REVIEW

**Review by robertodauria — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/11)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`cmd/jostler/main.go` line 79 at r1](https://reviewable.io/reviews/m-lab/jostler/11#-NGN-1Kx7xjMsdAwb70z:-NGN-1Kx7xjMsdAwb71-:b-em4bsa) ([raw file](https://github.com/m-lab/jostler/blob/03dfb4e8fa4b15171870cabd62f87571ead80795/cmd/jostler/main.go#L79)):*
> ```Go
> 	}
> 
> 	if strings.Contains(bucket, "fake") {
> ```

I would not introduce additional "testing" code paths in main if it can be avoided in any way. In this specific case, perhaps factory functions that return `schema` and `uploadbundle` and that can be swapped in main_test.go would work?

**Review by robertodauria — CHANGES_REQUESTED** [review]
Could you keep the functions together with the struct in the same file? Here `UploadBundle` is defined in uploadbundle.go while its functions are split among uploadbundle.go, upload.go and bundle.go.

If they are split because there are "upload" actions and "bundle" actions (as it seems to be the case) perhaps this is an opportunity for two distinct `Uploader` (`GCSUploader`) and `Bundler` (`JSONBundler`) abstractions? `UploadBundle` feels more like an `Uploader` than a `Bundle` since it uploads JSONBundles... does that make sense?

Please also add (at least some, not necessarily complete) unit tests and the CI integration before merging. This code is concurrent and complex enough that it is way beyond the "obviously correct by inspection" threshold.

> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/11#-:-NGRhpkF0cQfDJrwseUH:b-xwpazb)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`internal/uploadbundle/uploadbundle.go` line 38 at r1](https://reviewable.io/reviews/m-lab/jostler/11#-NGRmQTr1GXK8GyBoax4:-NGRmQTr1GXK8GyBoax5:bsko3hb) ([raw file](https://github.com/m-lab/jostler/blob/03dfb4e8fa4b15171870cabd62f87571ead80795/internal/uploadbundle/uploadbundle.go#L38)):*
> ```Go
> 	ageChan       chan *jsonlBundle       // notification channel for when bundle reaches maximum age
> 	activeBundles map[string]*jsonlBundle // bundles that are active
> 	uploadBundles map[string]struct{}     // bundles that are being uploaded or were uploaded
> ```

I think `uploadedBundles` would be a bit clearer and almost removes the need to look at the docstring. I feel like this still excludes "bundles that are being uploaded", but I'm having a hard time thinking of a name that includes both cases -- maybe `shippedBundles`? It doesn't imply they have arrived at destination. :slightly_smiling_face: 



_Code quote:_
```Go
uploadBundles
```
___
*[`test/data.go` line 1 at r1](https://reviewable.io/reviews/m-lab/jostler/11#-NGRokPiAFcIoWUNfRit:-NGRokPjElm8qbM4w9jJ:b-4bmbep) ([raw file](https://github.com/m-lab/jostler/blob/03dfb4e8fa4b15171870cabd62f87571ead80795/test/data.go#L1)):*
> ```Go
> package main
> ```

This is cool!

**Comment by SaiedKazemi** [comment]
*[`cmd/jostler/main.go` line 79 at r1](https://reviewable.io/reviews/m-lab/jostler/11#-NGN-1Kx7xjMsdAwb70z:-NGSpV_d3lRKW63Vb1aj:bht5wzx) ([raw file](https://github.com/m-lab/jostler/blob/03dfb4e8fa4b15171870cabd62f87571ead80795/cmd/jostler/main.go#L79)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I would not introduce additional "testing" code paths in main if it can be avoided in any way. In this specific case, perhaps factory functions that return `schema` and `uploadbundle` and that can be swapped in main_test.go would work?
</blockquote></details>

As we discussed offline, this is not meant to be permanent and used during the current phase of development and debugging.  That said, I changed the code to use a flag `-no-gcs` instead of the bucket name.  Also, I renamed `fakeXXX` to `diskXXX` to make it clearer that the disk storage is not pure fake and does mimic downloads from and uploads to GCS.

**Comment by SaiedKazemi** [comment]
*[`internal/uploadbundle/uploadbundle.go` line 38 at r1](https://reviewable.io/reviews/m-lab/jostler/11#-NGRmQTr1GXK8GyBoax4:-NGSr6RqEd_TSHBZvvCu:bu96bqu) ([raw file](https://github.com/m-lab/jostler/blob/03dfb4e8fa4b15171870cabd62f87571ead80795/internal/uploadbundle/uploadbundle.go#L38)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I think `uploadedBundles` would be a bit clearer and almost removes the need to look at the docstring. I feel like this still excludes "bundles that are being uploaded", but I'm having a hard time thinking of a name that includes both cases -- maybe `shippedBundles`? It doesn't imply they have arrived at destination. :slightly_smiling_face: 
</blockquote></details>

Yes, sometimes coming up with a good name is really difficult.  Does any of `closedBundles`, `processedBundles` or `readyBundles` sound good to you?

**Comment by SaiedKazemi** [comment]
*[`test/data.go` line 1 at r1](https://reviewable.io/reviews/m-lab/jostler/11#-NGRokPiAFcIoWUNfRit:-NGSuV8YAn7Pc1dB4r42:b-mlfkq0) ([raw file](https://github.com/m-lab/jostler/blob/03dfb4e8fa4b15171870cabd62f87571ead80795/test/data.go#L1)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

This is cool!
</blockquote></details>

I am glad you're finding it useful.  It can be further improved to create rare conditions.

**Comment by SaiedKazemi** [comment]
I looked for style guidelines about putting together all methods of a struct in the same file as the struct and didn't find any.  None of the linters complained either.  However, I changes you mentioned :). I also added unit tests for `uploadbundle`.  Coverage is 77% and I will continue to add more tests as go forward.

PTAL.

**Review by robertodauria — CHANGES_REQUESTED** [review]
Please don't add any new code to this PR -- it's already +1600 lines, and more than half of it is actual Go or bash code.

> I looked for style guidelines about putting together all methods of a struct in the same file as the struct and didn't find any. None of the linters complained either. However, I changes you mentioned :). I also added unit tests for uploadbundle. Coverage is 77% and I will continue to add more tests as go forward.

I don't believe there is an official guideline, but the separation of the struct and its methods into separate files made it hard for me to follow the logic. If the struct ends up having too many functions (i.e. too many responsibilities) it may be a sign that it needs to be split into separate structs with fewer responsibilities.

I still think `JSONL bundler` and `Upload bundler` are two separate abstractions that would be better in separate packages. They don't need to depend on each other's private members, each of them exposes its own public API that can be independently unit tested, and they could also be separately reused somewhere else in the future.

Would you be willing to split this PR in two, one for the json-bundling code and one for the upload code (regardless of how you decide to organize them)? Ideally they would not exceed 400-500 lines each including tests. The CI integration can be part of any of them or a third, separate PR. I'm happy to help with setting that up, if needed.

> Reviewed 1 of 12 files at r1, 4 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/jostler/11#-:-NGX8R0xB1QHDA41w31a:bs1l2pc)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`internal/uploadbundle/uploadbundle.go` line 38 at r1](https://reviewable.io/reviews/m-lab/jostler/11#-NGRmQTr1GXK8GyBoax4:-NGX6s80BklWQRGzjfj4:buyvc8m) ([raw file](https://github.com/m-lab/jostler/blob/03dfb4e8fa4b15171870cabd62f87571ead80795/internal/uploadbundle/uploadbundle.go#L38)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Yes, sometimes coming up with a good name is really difficult.  Does any of `closedBundles`, `processedBundles` or `readyBundles` sound good to you?
</blockquote></details>

`closed`: doesn't tell us they have been uploaded nor that they are being uploaded
`processed`: assuming the "process" in question is the upload, it doesn't include bundles that are being uploaded
`ready`: doesn't tell us they have been uploaded nor that they are being uploaded (unless you define what "ready" means in this context separately)

I have no real preference here (as long as it's documented, and it is) other than: if you want to keep the word "upload" in the name, make it `uploadedBundles` instead of `uploadBundles`.
___
*[`internal/uploadbundle/uploadbundle.go` line 38 at r2](https://reviewable.io/reviews/m-lab/jostler/11#-NGXEcNMAAsOVO1wkBQH:-NGXEcNMAAsOVO1wkBQI:b-3e822e) ([raw file](https://github.com/m-lab/jostler/blob/63829d94244b4d5c3817b558a9a0588758fb2a02/internal/uploadbundle/uploadbundle.go#L38)):*
> ```Go
> // common to all instances of JSONL bundles (see jsonlBundle).
> type UploadBundle struct {
> 	wdClient      watchdir.WatchDirClient // directory watcher that notifies us
> ```

It's generally better to define interfaces in the package where they are used, not where they are implemented. That way your package (uploadbundle, in this case) can only depend on the specific part of watchdir's behavior it actually needs (which may just be a subset of watchdir's behavior). This simplifies mocking and testing -- fewer functions to mock and no changes to make here if/when `watchdir.WatchDirClient` gets new functions in the future.

https://github.com/golang/go/wiki/CodeReviewComments#interfaces

```Go interfaces generally belong in the package that uses values of the interface type, not the package that implements those values. The implementing package should return concrete (usually pointer or struct) types: that way, new methods can be added to implementations without requiring extensive refactoring.```

**Comment by SaiedKazemi** [comment]
Sorry about the size of this PR.  The new code added in the last commit is for package unit testing which I had intended to submit in a future PR but you wanted me to add it to this PR (unless I misunderstood your comment).  Other changes are also only addressing code review comments.  Regarding files in the `test` directory, you don't have to review them because it's not part of `jostler` and I use it for my own e2e testing (`test` can be deleted from this repo).

Re splitting this package into two, I am open to the idea and there are two way to do it. (1) Submit a PR after this PR's review is done and merged or (2) Close this PR, split the package, and send send two new PRs.  I prefer (1) if you are not totally opposed to it.

**Comment by SaiedKazemi** [comment]
*[`internal/uploadbundle/uploadbundle.go` line 38 at r2](https://reviewable.io/reviews/m-lab/jostler/11#-NGXEcNMAAsOVO1wkBQH:-NGXP37mCD_pV8vjYVOl:b-xzimhn) ([raw file](https://github.com/m-lab/jostler/blob/63829d94244b4d5c3817b558a9a0588758fb2a02/internal/uploadbundle/uploadbundle.go#L38)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

It's generally better to define interfaces in the package where they are used, not where they are implemented. That way your package (uploadbundle, in this case) may only depend on the specific part of watchdir's behavior it actually needs (which can just be a subset of watchdir's behavior). This simplifies mocking and testing -- fewer functions to mock and no changes to make here if/when `watchdir.WatchDirClient` gets new functions in the future.

https://github.com/golang/go/wiki/CodeReviewComments#interfaces

```Go interfaces generally belong in the package that uses values of the interface type, not the package that implements those values. The implementing package should return concrete (usually pointer or struct) types: that way, new methods can be added to implementations without requiring extensive refactoring.```
</blockquote></details>

Yeah, I'm familiar with the guideline for defining interfaces and  either I missed this one or there was a reason to put it there.  I will look into it...

**Comment by SaiedKazemi** [comment]
*[`internal/uploadbundle/uploadbundle.go` line 38 at r1](https://reviewable.io/reviews/m-lab/jostler/11#-NGRmQTr1GXK8GyBoax4:-NGXPfQsBdd5QPt439F2:b-y5618q) ([raw file](https://github.com/m-lab/jostler/blob/03dfb4e8fa4b15171870cabd62f87571ead80795/internal/uploadbundle/uploadbundle.go#L38)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

`closed`: doesn't tell us they have been uploaded nor that they are being uploaded
`processed`: assuming the "process" in question is the upload, it doesn't include bundles that are being uploaded
`ready`: doesn't tell us they have been uploaded nor that they are being uploaded (unless you define what "ready" means in this context separately)

I have no real preference here (as long as it's documented, and it is) other than: if you want to keep the word "upload" in the name, make it `uploadedBundles` instead of `uploadBundles`.
</blockquote></details>

I'll change it to `uploadedBundles` although it suggests that bundles are already uploaded.

The motivation behind the name `uploadBundles` was to capture both `uploading` and `uploaded`.

**Comment by SaiedKazemi** [comment]
This PR was closed in favor of [this PR ](https://github.com/m-lab/jostler/pull/13).

**Pull request closed without merging**
